#!/bin/bash


for motl in "$@"
do
	avgstd=`awk '{ if ( NF > 1 ) print }' $motl | awk '{sc += $9; sc2+=$9^2} END { print sc/NR, sqrt((sc2-sc^2/NR)/NR) }'` 
	avg=`echo $avgstd | awk '{print $1}'`
	std=`echo $avgstd | awk '{print $2}'`
	echo "$motl average score: $avg, standard deviation: $std"                                                      
done

